# http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
    - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
