language: go

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=arm
  - GIMME_OS=linux GIMME_ARCH=arm64
  - GIMME_OS=darwin GIMME_ARCH=amd64

install:
  - go get -d -v ./...

script:
  - go build -v ./...
  - zip git-get-${GIMME_OS}-${GIMME_ARCH}-${TRAVIS_TAG}.zip git-get
  - tar czvf git-get-${GIMME_OS}-${GIMME_ARCH}-${TRAVIS_TAG}.tar.gz git-get

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mTgBgHo6FONIn7jAk/qVfhV2qPHA31U1J9YlNYs1qMmWwF9QjFGwU/ucfzYDGXLVFUUXL5j8oHRBPsvjyCUuiBEk3CMq6CatFgmSxeb/VBjLY3sqVC8ZKzNL5vXxw1wt6+d6VERERsfFWqnJz/nuWgzQeHJOwM8j9Gb0P/I+ndI=
  file_glob: true
  file:
    - git-get*.zip
    - git-get*.tar.gz
  on:
    repo: homburg/git-get
    tags: true
