name: goreleaser

on:
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master

      - name: Set up Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Set up Snapcraft login
        run: "echo ${{ secrets.SNAPCRAFT_LOGIN }} | base64 -d > snap.login"
        shell: bash

      - name: Login to snapcraft
        run: snapcraft login --with snap.login

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release
