name: goreleaser

# Build on tags on master
on:
  workflow_dispatch:
  create:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master

      # - name: Set up Snapcraft
      #   run: sudo snap install snapcraft --classic

      # - name: Login to Snapcraft
      #   env:
      #     SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
      #   run: sudo sh ./scripts/snapcraft-login.sh

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE_TOKEN }}
        with:
          version: latest
          args: release
